/**
 * API publique de la feature Workspace — espaces, pages, tâches.
 *
 * Modèle de données, RLS et triggers : supabase/migrations/20260929090000_workspace.sql.
 * Aucun écran ici : ils viendront avec la direction artistique retenue.
 */

export {
  EMPTY_DOCUMENT,
  TASK_PRIORITY_LABELS,
  TASK_STATUS_LABELS,
  archiveSpace,
  createPage,
  createSpace,
  createTask,
  deletePage,
  deleteTask,
  getPage,
  getPagePreference,
  listPageRevisions,
  listPages,
  listSpaces,
  listTasks,
  listTasksForMission,
  movePage,
  updatePagePresentation,
  savePage,
  setPageNotificationLevel,
  updateSpace,
  updateTask,
  COVERS_BUCKET,
  COVER_MAX_BYTES,
  COVER_MIME_TYPES,
  addFavorite,
  createPageFromTemplate,
  deleteTemplate,
  ensurePersonalSpace,
  getCoverUrl,
  isPersonalSpace,
  listFavorites,
  listRecentPages,
  listTemplates,
  removeFavorite,
  removePageCover,
  saveAsTemplate,
  searchPages,
  setPageIcon,
  textToTiptapDocument,
  touchPage,
  updateTemplate,
  uploadPageCover,
  AUDIO_BUCKET,
  AUDIO_MAX_BYTES,
  AUDIO_MAX_SECONDS,
  RECORDING_STATUS_LABELS,
  createRecording,
  createRecordingRow,
  submitRecording,
  deleteRecording,
  getRecordingAudioUrl,
  getTranscriptionQuota,
  listRecordings,
  renameRecording,
  VOCABULARY_TYPE_LABELS,
  addVocabularyTerms,
  listVocabulary,
  removeVocabularyTerm,
  suggestVocabulary,
  updateVocabularyTerm,
  type VocabularyEntry,
  type VocabularySuggestion,
  type CreateRecordingInput,
  type TranscriptionQuota,
  type WorkspaceRecording,
  type SavePageInput,
  type TaskFilters,
  type WorkspaceFavorite,
  type WorkspacePage,
  type WorkspacePagePreference,
  type WorkspacePageRevision,
  type WorkspaceRecentPage,
  type WorkspaceSearchHit,
  type WorkspaceSpace,
  type WorkspaceTask,
  type WorkspaceTemplate,
} from './api/workspace.api';

export {
  useArchiveSpace,
  useCreatePage,
  useCreateSpace,
  useCreateTask,
  useDeletePage,
  useDeleteTask,
  useMissionTasks,
  useMovePage,
  useUpdatePagePresentation,
  usePage,
  usePagePreference,
  usePageRevisions,
  usePages,
  useSavePage,
  useSetPageNotificationLevel,
  useSpaces,
  useTasks,
  useUpdateSpace,
  useUpdateTask,
  useCoverUrl,
  useCreatePageFromTemplate,
  useDeleteTemplate,
  useFavorites,
  usePersonalSpace,
  useRecentPages,
  useRemovePageCover,
  useSaveAsTemplate,
  useSearchPages,
  useSetPageIcon,
  useTemplates,
  useToggleFavorite,
  useTouchPage,
  useUpdateTemplate,
  useUploadPageCover,
  useCreateRecording,
  useDeleteRecording,
  useRecordingAudioUrl,
  useRecordings,
  useRenameRecording,
  useTranscriptionQuota,
  useAddVocabularyTerms,
  useRemoveVocabularyTerm,
  useUpdateVocabularyTerm,
  useVocabulary,
  useVocabularySuggestions,
} from './hooks/useWorkspace';

export {
  CAPTURE_BITRATE,
  CAPTURE_CONSTRAINTS,
  useAudioRecorder,
  type AudioRecorderStatus,
  type PendingRecording,
  type RecorderMedia,
  type RecorderServerApi,
  type StartOptions,
  type UseAudioRecorderOptions,
} from './hooks/useAudioRecorder';
export {
  IndexedDbAudioStore,
  MemoryAudioStore,
  createLocalAudioStore,
  type LocalAudioStore,
  type LocalRecording,
  type LocalRecordingStatus,
} from './audio/local-store';
export { uploadResumable, type ResumableUploader } from './audio/resumable-upload';
export { WorkspacePageOptionsPanel } from './components/WorkspacePageOptionsPanel';
