/**
 * API publique de la feature Workspace — espaces, pages, tâches.
 *
 * Modèle de données, RLS et triggers : supabase/migrations/20260929090000_workspace.sql.
 * Aucun écran ici : ils viendront avec la direction artistique retenue.
 */

export {
  EMPTY_DOCUMENT,
  TASK_PRIORITY_LABELS,
  TASK_STATUS_LABELS,
  archiveSpace,
  createPage,
  createSpace,
  createTask,
  deletePage,
  deleteTask,
  getPage,
  listPageRevisions,
  listPages,
  listSpaces,
  listTasks,
  listTasksForMission,
  movePage,
  savePage,
  updateSpace,
  updateTask,
  COVERS_BUCKET,
  COVER_MAX_BYTES,
  COVER_MIME_TYPES,
  addFavorite,
  createPageFromTemplate,
  deleteTemplate,
  ensurePersonalSpace,
  getCoverUrl,
  isPersonalSpace,
  listFavorites,
  listRecentPages,
  listTemplates,
  removeFavorite,
  removePageCover,
  saveAsTemplate,
  searchPages,
  setPageIcon,
  textToTiptapDocument,
  touchPage,
  updateTemplate,
  uploadPageCover,
  type SavePageInput,
  type TaskFilters,
  type WorkspaceFavorite,
  type WorkspacePage,
  type WorkspacePageRevision,
  type WorkspaceRecentPage,
  type WorkspaceSearchHit,
  type WorkspaceSpace,
  type WorkspaceTask,
  type WorkspaceTemplate,
} from './api/workspace.api';

export {
  useArchiveSpace,
  useCreatePage,
  useCreateSpace,
  useCreateTask,
  useDeletePage,
  useDeleteTask,
  useMissionTasks,
  useMovePage,
  usePage,
  usePageRevisions,
  usePages,
  useSavePage,
  useSpaces,
  useTasks,
  useUpdateSpace,
  useUpdateTask,
  useCoverUrl,
  useCreatePageFromTemplate,
  useDeleteTemplate,
  useFavorites,
  usePersonalSpace,
  useRecentPages,
  useRemovePageCover,
  useSaveAsTemplate,
  useSearchPages,
  useSetPageIcon,
  useTemplates,
  useToggleFavorite,
  useTouchPage,
  useUpdateTemplate,
  useUploadPageCover,
} from './hooks/useWorkspace';
