import {
  Archive,
  BarChart3,
  BookOpen,
  Building2,
  Cable,
  Calendar,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Contact,
  Cpu,
  CreditCard,
  Droplet,
  FileText,
  Calculator,
  LayoutDashboard,
  Network,
  ScrollText,
  Settings,
  Star,
  User,
  Users,
  UsersRound,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  archive: Archive,
  tools: Wrench,
  star: Star,
  history: Clock,
  book: BookOpen,
  user: User,
  settings: Settings,
  building: Building2,
  users: Users,
  'users-round': UsersRound,
  contact: Contact,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  scroll: ScrollText,
  'credit-card': CreditCard,
  calendar: Calendar,
  zap: Zap,
  cable: Cable,
  network: Network,
  cpu: Cpu,
  wrench: Wrench,
  droplet: Droplet,
  chart: BarChart3,
  'file-text': FileText,
  calculator: Calculator,
};

export const FALLBACK_NAV_ICON: LucideIcon = Wrench;
