import {
  Activity,
  Archive,
  ArrowDownRight,
  ArrowLeftRight,
  BarChart2,
  BarChart3,
  BatteryCharging,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  Calendar,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Contact,
  Cpu,
  CreditCard,
  Droplet,
  FileText,
  Flame,
  Flower,
  Footprints,
  Gauge,
  GitCommit,
  Grid,
  Hammer,
  Home,
  LayoutDashboard,
  Layers,
  Map,
  Mountain,
  Network,
  Package,
  Paintbrush,
  Pickaxe,
  Scale,
  ScrollText,
  Settings,
  ShowerHead,
  ShoppingCart,
  Sparkles,
  Split,
  Sprout,
  Star,
  Store,
  Table,
  TreePine,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  Users,
  UsersRound,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  archive: Archive,
  tools: Wrench,
  star: Star,
  history: Clock,
  book: BookOpen,
  user: User,
  settings: Settings,
  building: Building2,
  users: Users,
  'users-round': UsersRound,
  truck: Truck,
  contact: Contact,
  clipboard: ClipboardList,
  'clipboard-check': ClipboardCheck,
  map: Map,
  scroll: ScrollText,
  'credit-card': CreditCard,
  calendar: Calendar,
  zap: Zap,
  cable: Cable,
  network: Network,
  cpu: Cpu,
  wrench: Wrench,
  droplet: Droplet,
  chart: BarChart3,
  'file-text': FileText,
  calculator: Calculator,
  sparkles: Sparkles,
  bot: Bot,
  package: Package,
  boxes: Boxes,
  'arrow-left-right': ArrowLeftRight,
  'shopping-cart': ShoppingCart,
  store: Store,
  briefcase: Briefcase,
  hammer: Hammer,
  flower: Flower,
  pickaxe: Pickaxe,
  mountain: Mountain,
  footprints: Footprints,
  home: Home,
  paintbrush: Paintbrush,
  scale: Scale,
  sprout: Sprout,
  'tree-pine': TreePine,
  gauge: Gauge,
  'battery-charging': BatteryCharging,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'shower-head': ShowerHead,
  activity: Activity,
  'circle-dot': CircleDot,
  'arrow-down-right': ArrowDownRight,
  flame: Flame,
  'git-commit': GitCommit,
  table: Table,
  split: Split,
  layers: Layers,
  box: Box,
  grid: Grid,
  'bar-chart-2': BarChart2,
};

export const FALLBACK_NAV_ICON: LucideIcon = Wrench;
