import type { TechnicianLocation, InterventionSite } from './types';

// Paris region center & coordinates
export const DEFAULT_MAP_CENTER = { lat: 48.8566, lng: 2.3522 };

export const INITIAL_TECHNICIANS: TechnicianLocation[] = [
  {
    id: 'tech-1',
    name: 'Aurélie B.',
    initials: 'AB',
    role: 'Technicienne Spécialiste',
    phone: '+33 6 12 34 56 78',
    trade: 'hvac',
    tradeLabel: 'Climatisation & Chauffage',
    status: 'on_road',
    currentLat: 48.8708,
    currentLng: 2.3045,
    heading: 75,
    speedKmH: 42,
    batteryPct: 88,
    lastPing: 'Il y a 12s',
    vehiclePlate: 'FX-892-TK',
    currentMission: {
      id: 'm-101',
      title: 'Dépannage PAC & Réparation Chaudière',
      reference: 'PAC-2026-08',
      clientName: 'Résidence Haussmann Étoile',
      clientAddress: '42 Avenue de Friedland, 75008 Paris',
      clientPhone: '+33 1 45 67 89 00',
      destinationLat: 48.8752,
      destinationLng: 2.3011,
      etaMinutes: 8,
      estimatedArrival: '14h25',
      progressPct: 65,
    },
    historyTrail: [
      { lat: 48.8350, lng: 2.2700, time: '08:15', speedKmH: 0, heading: 0, batteryPct: 100, status: 'available', note: 'Départ dépôt' },
      { lat: 48.8450, lng: 2.2850, time: '09:00', speedKmH: 35, heading: 45, batteryPct: 96, status: 'on_road' },
      { lat: 48.8550, lng: 2.2950, time: '09:45', speedKmH: 0, heading: 45, batteryPct: 94, status: 'on_site', note: 'Entretien annuel' },
      { lat: 48.8620, lng: 2.3000, time: '12:30', speedKmH: 0, heading: 0, batteryPct: 90, status: 'available', note: 'Pause déjeuner' },
      { lat: 48.8708, lng: 2.3045, time: '14:15', speedKmH: 42, heading: 75, batteryPct: 88, status: 'on_road', note: 'En route intervention urgente' },
    ],
  },
  {
    id: 'tech-2',
    name: 'Thomas R.',
    initials: 'TR',
    role: 'Technicien Télécoms & Fibre',
    phone: '+33 6 98 76 54 32',
    trade: 'fiber_telecom',
    tradeLabel: 'Fibre Optique FTTH/FTTO',
    status: 'on_site',
    currentLat: 48.8412,
    currentLng: 2.3685,
    heading: 180,
    speedKmH: 0,
    batteryPct: 64,
    lastPing: 'Il y a 5s',
    vehiclePlate: 'GL-441-BZ',
    currentMission: {
      id: 'm-102',
      title: 'Raccordement Immeuble & Réflectométrie',
      reference: 'FBR-75-992',
      clientName: 'Bureaux Tech Square',
      clientAddress: '18 Rue de Bercy, 75012 Paris',
      clientPhone: '+33 1 40 12 34 56',
      destinationLat: 48.8412,
      destinationLng: 2.3685,
      etaMinutes: 0,
      estimatedArrival: 'Sur place',
      progressPct: 80,
    },
    historyTrail: [
      { lat: 48.8350, lng: 2.2700, time: '08:00', speedKmH: 0, heading: 0, batteryPct: 100, status: 'available' },
      { lat: 48.8380, lng: 2.3200, time: '08:45', speedKmH: 50, heading: 90, batteryPct: 95, status: 'on_road' },
      { lat: 48.8412, lng: 2.3685, time: '09:30', speedKmH: 0, heading: 180, batteryPct: 75, status: 'on_site', note: 'Soudure cassettes fibre' },
    ],
  },
  {
    id: 'tech-3',
    name: 'Karim M.',
    initials: 'KM',
    role: 'Chef d\'Équipe Électricité',
    phone: '+33 6 45 12 89 74',
    trade: 'electrical',
    tradeLabel: 'Électricité & Courant Fort',
    status: 'on_road',
    currentLat: 48.8890,
    currentLng: 2.3420,
    heading: 320,
    speedKmH: 38,
    batteryPct: 92,
    lastPing: 'Il y a 20s',
    vehiclePlate: 'EV-310-NP',
    currentMission: {
      id: 'm-103',
      title: 'Mise en conformité TGBT & Disjoncteurs',
      reference: 'ELEC-2026-44',
      clientName: 'Clinique Montmartre',
      clientAddress: '12 Rue Caulaincourt, 75018 Paris',
      clientPhone: '+33 1 53 06 70 00',
      destinationLat: 48.8920,
      destinationLng: 2.3380,
      etaMinutes: 12,
      estimatedArrival: '14h30',
      progressPct: 40,
    },
    historyTrail: [
      { lat: 48.8350, lng: 2.2700, time: '08:15', speedKmH: 0, heading: 0, batteryPct: 100, status: 'available' },
      { lat: 48.8890, lng: 2.3420, time: '14:10', speedKmH: 38, heading: 320, batteryPct: 92, status: 'on_road' },
    ],
  },
  {
    id: 'tech-4',
    name: 'Sophie L.',
    initials: 'SL',
    role: 'Spécialiste Paysage & Environnement',
    phone: '+33 6 77 88 99 00',
    trade: 'landscaping',
    tradeLabel: 'Paysagisme & Espaces Verts',
    status: 'on_site',
    currentLat: 48.8285,
    currentLng: 2.3120,
    heading: 0,
    speedKmH: 0,
    batteryPct: 78,
    lastPing: 'Il y a 3s',
    vehiclePlate: 'PA-901-VE',
    currentMission: {
      id: 'm-104',
      title: 'Aménagement paysager & Arrosage auto',
      reference: 'PAY-75-018',
      clientName: 'Parc Tertiaire Montrouge',
      clientAddress: '5 Boulevard Romain Rolland, 75014 Paris',
      clientPhone: '+33 1 46 55 10 20',
      destinationLat: 48.8285,
      destinationLng: 2.3120,
      etaMinutes: 0,
      estimatedArrival: 'Sur place',
      progressPct: 90,
    },
    historyTrail: [
      { lat: 48.8350, lng: 2.2700, time: '08:00', speedKmH: 0, heading: 0, batteryPct: 100, status: 'available' },
      { lat: 48.8285, lng: 2.3120, time: '09:15', speedKmH: 0, heading: 0, batteryPct: 85, status: 'on_site' },
    ],
  },
];

export const INITIAL_INTERVENTIONS: InterventionSite[] = [
  {
    id: 'site-1',
    reference: 'PAC-2026-08',
    title: 'Dépannage PAC & Réparation Chaudière',
    trade: 'hvac',
    tradeLabel: 'HVAC / Climatisation',
    clientName: 'Résidence Haussmann Étoile',
    address: '42 Avenue de Friedland, 75008 Paris',
    lat: 48.8752,
    lng: 2.3011,
    priority: 'urgent',
    scheduledTime: '14:00 - 16:30',
    assignedTechnicianName: 'Aurélie B.',
    status: 'in_progress',
  },
  {
    id: 'site-2',
    reference: 'FBR-75-992',
    title: 'Raccordement Immeuble FTTO',
    trade: 'fiber_telecom',
    tradeLabel: 'Fibre Optique',
    clientName: 'Bureaux Tech Square',
    address: '18 Rue de Bercy, 75012 Paris',
    lat: 48.8412,
    lng: 2.3685,
    priority: 'high',
    scheduledTime: '09:30 - 15:00',
    assignedTechnicianName: 'Thomas R.',
    status: 'in_progress',
  },
  {
    id: 'site-3',
    reference: 'ELEC-2026-44',
    title: 'Mise en conformité TGBT',
    trade: 'electrical',
    tradeLabel: 'Électricité BT',
    clientName: 'Clinique Montmartre',
    address: '12 Rue Caulaincourt, 75018 Paris',
    lat: 48.8920,
    lng: 2.3380,
    priority: 'high',
    scheduledTime: '14:30 - 17:30',
    assignedTechnicianName: 'Karim M.',
    status: 'planned',
  },
  {
    id: 'site-4',
    reference: 'PAY-75-018',
    title: 'Aménagement paysager',
    trade: 'landscaping',
    tradeLabel: 'Paysagisme',
    clientName: 'Parc Tertiaire Montrouge',
    address: '5 Boulevard Romain Rolland, 75014 Paris',
    lat: 48.8285,
    lng: 2.3120,
    priority: 'normal',
    scheduledTime: '09:00 - 16:00',
    assignedTechnicianName: 'Sophie L.',
    status: 'in_progress',
  },
  {
    id: 'site-5',
    reference: 'PLB-75-302',
    title: 'Remplacement Colonne Générale',
    trade: 'plumbing',
    tradeLabel: 'Plomberie Sanitaire',
    clientName: 'Syndic République',
    address: '14 Place de la République, 75011 Paris',
    lat: 48.8675,
    lng: 2.3638,
    priority: 'urgent',
    scheduledTime: '16:00 - 18:30',
    status: 'planned',
  },
];
